Tt 727 update lib
aonec/tt-spa pull request #1848
Opened 2024-09-16 14:44 UTC by anotherIlnaz

2024-09-19 15:46 UTC, azizmuradovar requested changes

2024-09-19 15:46 UTC, azizmuradovar commented on src/services/devices/devicesPageService/individualDevicesProfileService/view/IndividualDevicesProfile/individualDevicesListService/view/IndividualDevicesList/IndividualDeviceConsumptionGraph/IndividualDeviceConsumptionGraph.tsx
> +          tickFormat={(date: any) =>
а почему any?

2024-09-19 15:46 UTC, azizmuradovar commented on src/services/nodes/displayNodesStatisticsService/view/StatisticsGraph/StatisticsGraph.tsx
> +          tickFormat={(x: any) =>
и тут почему any?

2024-09-19 15:46 UTC, azizmuradovar commented on package.json
> +    "lint-staged": "^15.2.10",
тут все отрабатывает?

2024-09-19 15:46 UTC, azizmuradovar commented on package.json
> +    "typescript": "^5.6.2",
тут что в мажорке обновилось?

2024-09-19 15:46 UTC, azizmuradovar commented on package.json
> +    "victory": "^37.1.1",
тут только что ниже? давай типы поправим

2024-09-20 08:12 UTC, anotherIlnaz commented on package.json
> +    "lint-staged": "^15.2.10",
Да

2024-09-20 08:13 UTC, anotherIlnaz commented on package.json
> +    "typescript": "^5.6.2",
1) typescript
2) victory (графики)
3) lint-staged

2024-09-24 08:18 UTC, merged